Repository shirtol/Website_Building, pull requests merged in 2022-05, with the labels that each got.

#8 Fetched and organized data object
  script/Student.js
  script/script.js
Labels: enhancement

#11 Sort function-in Progress
  index.html
  script/StudentUI.js
  script/StudentsController.js
  script/script.js
  style/style.css
Labels: enhancement

#13 Sort function
  script/StudentsController.js
  script/script.js
Labels: enhancement

#14 delete and header
  index.html
  script/StudentUI.js
  script/script.js
  style/style.css
Labels: enhancement

#18 Fixed sort function
  index.html
  script/StudentsController.js
  style/style.css
Labels: bug

#19 Fixed sort hidden rows
  index.html
  script/StudentUI.js
  style/style.css
Labels: bug

#20 Dataupdate
  script/script.js
Labels: bug

#21 enter and escape
  script/script.js
Labels: enhancement

#22 Responsiveness and more styling
  index.html
  script/StudentUI.js
  script/StudentsController.js
  style/style.css
Labels: enhancement

#23 Added appleseeds style
  style/style.css
Labels: enhancement

#24 Weather
  script/script.js
Labels: enhancement

#25 final project
  index.html
  script/StudentUI.js
  script/script.js
  style/style.css
Labels: enhancement

#26 Added icon and fixed search bug.
  ico/database_table.ico
  index.html
  script/Student.js
  script/script.js
Labels: bug, enhancement

#27 removed console.logs
  script/StudentUI.js
  script/StudentsController.js
Labels: documentation
